SET @preparedStatement = (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
	WHERE table_schema='topsys' AND table_name='con_obras' AND column_name='id_imp_is'
) > 0, 'SELECT 1;', 'ALTER TABLE `topsys`.`con_obras` ADD COLUMN `id_imp_is` INT(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `tribcontrib_nfs`;'));
PREPARE alterIfNotExists FROM @preparedStatement;
EXECUTE alterIfNotExists;
DEALLOCATE PREPARE alterIfNotExists;

SET @preparedStatement = (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
	WHERE table_schema='topsys' AND table_name='con_obras' AND column_name='id_imp_cbs'
) > 0, 'SELECT 1;', 'ALTER TABLE `topsys`.`con_obras` ADD COLUMN `id_imp_cbs` INT(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `id_imp_is`;'));
PREPARE alterIfNotExists FROM @preparedStatement;
EXECUTE alterIfNotExists;
DEALLOCATE PREPARE alterIfNotExists;

SET @preparedStatement = (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
	WHERE table_schema='topsys' AND table_name='con_obras' AND column_name='id_imp_ibs'
) > 0, 'SELECT 1;', 'ALTER TABLE `topsys`.`con_obras` ADD COLUMN `id_imp_ibs` INT(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `id_imp_cbs`;'));
PREPARE alterIfNotExists FROM @preparedStatement;
EXECUTE alterIfNotExists;
DEALLOCATE PREPARE alterIfNotExists;

SET @preparedStatement = (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
	WHERE table_schema='topsys' AND table_name='con_obras_versao' AND column_name='id_imp_is'
) > 0, 'SELECT 1;', 'ALTER TABLE `topsys`.`con_obras_versao` ADD COLUMN `id_imp_is` INT(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `tribcontrib_nfs`;'));
PREPARE alterIfNotExists FROM @preparedStatement;
EXECUTE alterIfNotExists;
DEALLOCATE PREPARE alterIfNotExists;

SET @preparedStatement = (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
	WHERE table_schema='topsys' AND table_name='con_obras_versao' AND column_name='id_imp_cbs'
) > 0, 'SELECT 1;', 'ALTER TABLE `topsys`.`con_obras_versao` ADD COLUMN `id_imp_cbs` INT(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `id_imp_is`;'));
PREPARE alterIfNotExists FROM @preparedStatement;
EXECUTE alterIfNotExists;
DEALLOCATE PREPARE alterIfNotExists;

SET @preparedStatement = (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
	WHERE table_schema='topsys' AND table_name='con_obras_versao' AND column_name='id_imp_ibs'
) > 0, 'SELECT 1;', 'ALTER TABLE `topsys`.`con_obras_versao` ADD COLUMN `id_imp_ibs` INT(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `id_imp_cbs`;'));
PREPARE alterIfNotExists FROM @preparedStatement;
EXECUTE alterIfNotExists;
DEALLOCATE PREPARE alterIfNotExists;

ALTER TABLE con_obras
    MODIFY COLUMN `usina` smallint(3) unsigned NOT NULL DEFAULT '0' FIRST,
    MODIFY COLUMN `numero` mediumint(6) unsigned NOT NULL DEFAULT '0' AFTER `usina`,
    MODIFY COLUMN `ano_levto` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `numero`,
    MODIFY COLUMN `no_levto` mediumint(5) unsigned NOT NULL DEFAULT '0' AFTER `ano_levto`,
    MODIFY COLUMN `ano_visita` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `no_levto`,
    MODIFY COLUMN `no_visita` mediumint(5) unsigned NOT NULL DEFAULT '0' AFTER `ano_visita`,
    MODIFY COLUMN `ano_chamada` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `no_visita`,
    MODIFY COLUMN `no_chamada` mediumint(5) unsigned NOT NULL DEFAULT '0' AFTER `ano_chamada`,
    MODIFY COLUMN `ano_proposta` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `no_chamada`,
    MODIFY COLUMN `no_proposta` mediumint(5) unsigned NOT NULL DEFAULT '0' AFTER `ano_proposta`,
    MODIFY COLUMN `ano_contrato` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `no_proposta`,
    MODIFY COLUMN `no_contrato` mediumint(5) unsigned NOT NULL DEFAULT '0' AFTER `ano_contrato`,
    MODIFY COLUMN `obra_nome` char(30) NOT NULL DEFAULT '' AFTER `no_contrato`,
    MODIFY COLUMN `obra_cep` char(8) NOT NULL DEFAULT '' AFTER `obra_nome`,
    MODIFY COLUMN `obra_end` char(40) NOT NULL DEFAULT '' AFTER `obra_cep`,
    MODIFY COLUMN `obra_num` mediumint(6) unsigned NOT NULL DEFAULT '0' AFTER `obra_end`,
    MODIFY COLUMN `obra_compl` char(30) NOT NULL DEFAULT '' AFTER `obra_num`,
    MODIFY COLUMN `obra_bairro` char(20) NOT NULL DEFAULT '' AFTER `obra_compl`,
    MODIFY COLUMN `obra_mun` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `obra_bairro`,
    MODIFY COLUMN `email` char(255) NOT NULL DEFAULT '' AFTER `obra_mun`,
    MODIFY COLUMN `obra_usina` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `email`,
    MODIFY COLUMN `obra_km_usina` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `obra_usina`,
    MODIFY COLUMN `obra_km_usina_via_google` smallint(3) unsigned DEFAULT '0' AFTER `obra_km_usina`,
    MODIFY COLUMN `obra_prev_inic` date AFTER `obra_km_usina_via_google`,
    MODIFY COLUMN `obra_prev_term` date AFTER `obra_prev_inic`,
    MODIFY COLUMN `obra_prazo` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `obra_prev_term`,
    MODIFY COLUMN `obra_tipo` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `obra_prazo`,
    MODIFY COLUMN `obra_porte` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `obra_tipo`,
    MODIFY COLUMN `obra_fase` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `obra_porte`,
    MODIFY COLUMN `fase_concorrenc` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `obra_fase`,
    MODIFY COLUMN `obra_topografia` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `fase_concorrenc`,
    MODIFY COLUMN `obra_acesso` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `obra_topografia`,
    MODIFY COLUMN `obra_vl_pedagio` float(5,2) unsigned NOT NULL DEFAULT '0.00' AFTER `obra_acesso`,
    MODIFY COLUMN `obra_zrmc` char(1) NOT NULL DEFAULT '' AFTER `obra_vl_pedagio`,
    MODIFY COLUMN `obra_proib_est` char(1) NOT NULL DEFAULT '' AFTER `obra_zrmc`,
    MODIFY COLUMN `obra_fio_tensao` char(1) NOT NULL DEFAULT '' AFTER `obra_proib_est`,
    MODIFY COLUMN `obra_zona_azul` char(1) NOT NULL DEFAULT '' AFTER `obra_fio_tensao`,
    MODIFY COLUMN `obra_nova` char(1) NOT NULL DEFAULT '' AFTER `obra_zona_azul`,
    MODIFY COLUMN `obra_inic_conc` char(1) NOT NULL DEFAULT '' AFTER `obra_nova`,
    MODIFY COLUMN `obra_contato` char(30) NOT NULL DEFAULT '' AFTER `obra_inic_conc`,
    MODIFY COLUMN `obra_cont_func` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `obra_contato`,
    MODIFY COLUMN `obra_cont_fone` int(9) unsigned NOT NULL DEFAULT '0' AFTER `obra_cont_func`,
    MODIFY COLUMN `obra_cont_cel` int(9) unsigned NOT NULL DEFAULT '0' AFTER `obra_cont_fone`,
    MODIFY COLUMN `obra_contato1` char(30) NOT NULL DEFAULT '' AFTER `obra_cont_cel`,
    MODIFY COLUMN `obra_cont1_func` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `obra_contato1`,
    MODIFY COLUMN `obra_cont1_fone` int(9) unsigned NOT NULL DEFAULT '0' AFTER `obra_cont1_func`,
    MODIFY COLUMN `obra_cont1_cel` int(9) unsigned NOT NULL DEFAULT '0' AFTER `obra_cont1_fone`,
    MODIFY COLUMN `obra_captado_v` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `obra_cont1_cel`,
    MODIFY COLUMN `obra_refer_aces` text AFTER `obra_captado_v`,
    MODIFY COLUMN `obra_pct_rp_cim` float(4,2) unsigned NOT NULL DEFAULT '0.00' AFTER `obra_refer_aces`,
    MODIFY COLUMN `obra_pct_rp_ped` float(4,2) unsigned NOT NULL DEFAULT '0.00' AFTER `obra_pct_rp_cim`,
    MODIFY COLUMN `obra_pct_rp_are` float(4,2) unsigned NOT NULL DEFAULT '0.00' AFTER `obra_pct_rp_ped`,
    MODIFY COLUMN `obra_pct_rp_obr` float(4,2) unsigned NOT NULL DEFAULT '0.00' AFTER `obra_pct_rp_are`,
    MODIFY COLUMN `obra_pct_rp_die` float(4,2) unsigned NOT NULL DEFAULT '0.00' AFTER `obra_pct_rp_obr`,
    MODIFY COLUMN `concorrente` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `obra_pct_rp_die`,
    MODIFY COLUMN `id_cadast` char(19) NOT NULL DEFAULT '' AFTER `concorrente`,
    MODIFY COLUMN `id_atual` char(19) NOT NULL DEFAULT '' AFTER `id_cadast`,
    MODIFY COLUMN `obra_resultado` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `id_atual`,
    MODIFY COLUMN `obra_desist` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `obra_resultado`,
    MODIFY COLUMN `obra_dt_desist` date AFTER `obra_desist`,
    MODIFY COLUMN `obra_usina_sec` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `obra_dt_desist`,
    MODIFY COLUMN `obra_km_usina_s` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `obra_usina_sec`,
    MODIFY COLUMN `volume_concreto` float(7,1) unsigned NOT NULL DEFAULT '0.0' AFTER `obra_km_usina_s`,
    MODIFY COLUMN `cond_pgto` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `volume_concreto`,
    MODIFY COLUMN `tipo_cobranca` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `cond_pgto`,
    MODIFY COLUMN `ganhou` char(1) NOT NULL DEFAULT '' AFTER `tipo_cobranca`,
    MODIFY COLUMN `reaj_id_solic` char(19) NOT NULL DEFAULT '' AFTER `ganhou`,
    MODIFY COLUMN `reaj_aprov_verb` char(1) NOT NULL DEFAULT '' AFTER `reaj_id_solic`,
    MODIFY COLUMN `reaj_id_aprov` char(19) NOT NULL DEFAULT '' AFTER `reaj_aprov_verb`,
    MODIFY COLUMN `obs` varchar(1000) NOT NULL AFTER `reaj_id_aprov`,
    MODIFY COLUMN `bco_cobranca` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `obs`,
    MODIFY COLUMN `reaj_sts_aprov` char(1) NOT NULL DEFAULT '' AFTER `bco_cobranca`,
    MODIFY COLUMN `reaj_cien_aprov` char(1) NOT NULL DEFAULT '' AFTER `reaj_sts_aprov`,
    MODIFY COLUMN `cp_prv_tipo` char(8) NOT NULL DEFAULT '' AFTER `reaj_cien_aprov`,
    MODIFY COLUMN `cp_prv_qtde` tinyint(1) unsigned NOT NULL DEFAULT '0' AFTER `cp_prv_tipo`,
    MODIFY COLUMN `cp_prv_intvl_m3` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `cp_prv_qtde`,
    MODIFY COLUMN `intinerante` char(1) NOT NULL DEFAULT '' AFTER `cp_prv_intvl_m3`,
    MODIFY COLUMN `seq` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `intinerante`,
    MODIFY COLUMN `obra_cont_ddd` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `seq`,
    MODIFY COLUMN `obra_cont_ddd1` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `obra_cont_ddd`,
    MODIFY COLUMN `vibr_qtde` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `obra_cont_ddd1`,
    MODIFY COLUMN `vibr_vlr_unit` float(6,2) unsigned NOT NULL DEFAULT '0.00' AFTER `vibr_qtde`,
    MODIFY COLUMN `volume_pcarga` float(5,1) unsigned NOT NULL DEFAULT '0.0' AFTER `vibr_vlr_unit`,
    MODIFY COLUMN `obra_cel_ddd` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `volume_pcarga`,
    MODIFY COLUMN `obra_cel_ddd1` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `obra_cel_ddd`,
    MODIFY COLUMN `obra_radio` char(15) NOT NULL DEFAULT '' AFTER `obra_cel_ddd1`,
    MODIFY COLUMN `temp_ate_a_obra` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `obra_radio`,
    MODIFY COLUMN `temp_bt_na_obra` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `temp_ate_a_obra`,
    MODIFY COLUMN `url_mapa_obra` char(200) NOT NULL DEFAULT '' AFTER `temp_bt_na_obra`,
    MODIFY COLUMN `status_comercial` tinyint(1) unsigned NOT NULL DEFAULT '0' AFTER `url_mapa_obra`,
    MODIFY COLUMN `status_cadastro` tinyint(1) unsigned NOT NULL DEFAULT '0' AFTER `status_comercial`,
    MODIFY COLUMN `status_financeiro` tinyint(1) unsigned NOT NULL DEFAULT '0' AFTER `status_cadastro`,
    MODIFY COLUMN `status_engenharia` tinyint(1) unsigned NOT NULL DEFAULT '0' AFTER `status_financeiro`,
    MODIFY COLUMN `vlr_demais_servicos` double(8,2) unsigned NOT NULL DEFAULT '0.00' AFTER `status_engenharia`,
    MODIFY COLUMN `obra_cei` varchar(12) NOT NULL DEFAULT '' AFTER `vlr_demais_servicos`,
    MODIFY COLUMN `obra_obs` varchar(1000) NOT NULL DEFAULT '' AFTER `obra_cei`,
    MODIFY COLUMN `tempo_ciclo_prev` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `obra_obs`,
    MODIFY COLUMN `custo_proje_trans` float(6,2) unsigned NOT NULL DEFAULT '0.00' AFTER `tempo_ciclo_prev`,
    MODIFY COLUMN `obra_benef_fiscal` varchar(45) DEFAULT '' AFTER `custo_proje_trans`,
    MODIFY COLUMN `rota_padrao` char(36) AFTER `obra_benef_fiscal`,
    MODIFY COLUMN `email_resp_tecnico` varchar(255) DEFAULT '' AFTER `rota_padrao`,
    MODIFY COLUMN `tribcontrib_nfs` char(4) NOT NULL DEFAULT '' AFTER `email_resp_tecnico`,
    MODIFY COLUMN `id_imp_is` int(11) unsigned NOT NULL DEFAULT '0' AFTER `tribcontrib_nfs`,
    MODIFY COLUMN `id_imp_cbs` int(11) unsigned NOT NULL DEFAULT '0' AFTER `id_imp_is`,
    MODIFY COLUMN `id_imp_ibs` int(11) unsigned NOT NULL DEFAULT '0' AFTER `id_imp_cbs`,
    MODIFY COLUMN `volume_status_comercial` tinyint(4) NOT NULL DEFAULT '0' AFTER `id_imp_ibs`,
    MODIFY COLUMN `usa_adicional_zmrc` char(1) NOT NULL DEFAULT 'N' AFTER `volume_status_comercial`,
    MODIFY COLUMN `necessita_aprov_zmrc` char(1) NOT NULL DEFAULT 'N' AFTER `usa_adicional_zmrc`,
    MODIFY COLUMN `condicao_pagamento_status_comercial` tinyint(4) NOT NULL DEFAULT '0' AFTER `necessita_aprov_zmrc`,
    MODIFY COLUMN `tempo_descarga` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `condicao_pagamento_status_comercial`;

ALTER TABLE con_obras_versao
    MODIFY COLUMN `usina` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `num_versao`,
    MODIFY COLUMN `numero` mediumint(6) unsigned NOT NULL DEFAULT '0' AFTER `usina`,
    MODIFY COLUMN `ano_levto` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `numero`,
    MODIFY COLUMN `no_levto` mediumint(5) unsigned NOT NULL DEFAULT '0' AFTER `ano_levto`,
    MODIFY COLUMN `ano_visita` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `no_levto`,
    MODIFY COLUMN `no_visita` mediumint(5) unsigned NOT NULL DEFAULT '0' AFTER `ano_visita`,
    MODIFY COLUMN `ano_chamada` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `no_visita`,
    MODIFY COLUMN `no_chamada` mediumint(5) unsigned NOT NULL DEFAULT '0' AFTER `ano_chamada`,
    MODIFY COLUMN `ano_proposta` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `no_chamada`,
    MODIFY COLUMN `no_proposta` mediumint(5) unsigned NOT NULL DEFAULT '0' AFTER `ano_proposta`,
    MODIFY COLUMN `ano_contrato` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `no_proposta`,
    MODIFY COLUMN `no_contrato` mediumint(5) unsigned NOT NULL DEFAULT '0' AFTER `ano_contrato`,
    MODIFY COLUMN `obra_nome` char(30) NOT NULL DEFAULT '' AFTER `no_contrato`,
    MODIFY COLUMN `obra_cep` char(8) NOT NULL DEFAULT '' AFTER `obra_nome`,
    MODIFY COLUMN `obra_end` char(40) NOT NULL DEFAULT '' AFTER `obra_cep`,
    MODIFY COLUMN `obra_num` mediumint(6) unsigned NOT NULL DEFAULT '0' AFTER `obra_end`,
    MODIFY COLUMN `obra_compl` char(30) NOT NULL DEFAULT '' AFTER `obra_num`,
    MODIFY COLUMN `obra_bairro` char(20) NOT NULL DEFAULT '' AFTER `obra_compl`,
    MODIFY COLUMN `obra_mun` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `obra_bairro`,
    MODIFY COLUMN `email` char(255) NOT NULL DEFAULT '' AFTER `obra_mun`,
    MODIFY COLUMN `obra_usina` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `email`,
    MODIFY COLUMN `obra_km_usina` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `obra_usina`,
    MODIFY COLUMN `obra_km_usina_via_google` smallint(3) unsigned DEFAULT '0' AFTER `obra_km_usina`,
    MODIFY COLUMN `obra_prev_inic` date AFTER `obra_km_usina_via_google`,
    MODIFY COLUMN `obra_prev_term` date AFTER `obra_prev_inic`,
    MODIFY COLUMN `obra_prazo` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `obra_prev_term`,
    MODIFY COLUMN `obra_tipo` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `obra_prazo`,
    MODIFY COLUMN `obra_porte` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `obra_tipo`,
    MODIFY COLUMN `obra_fase` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `obra_porte`,
    MODIFY COLUMN `fase_concorrenc` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `obra_fase`,
    MODIFY COLUMN `obra_topografia` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `fase_concorrenc`,
    MODIFY COLUMN `obra_acesso` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `obra_topografia`,
    MODIFY COLUMN `obra_vl_pedagio` float(5,2) unsigned NOT NULL DEFAULT '0.00' AFTER `obra_acesso`,
    MODIFY COLUMN `obra_zrmc` char(1) NOT NULL DEFAULT '' AFTER `obra_vl_pedagio`,
    MODIFY COLUMN `obra_proib_est` char(1) NOT NULL DEFAULT '' AFTER `obra_zrmc`,
    MODIFY COLUMN `obra_fio_tensao` char(1) NOT NULL DEFAULT '' AFTER `obra_proib_est`,
    MODIFY COLUMN `obra_zona_azul` char(1) NOT NULL DEFAULT '' AFTER `obra_fio_tensao`,
    MODIFY COLUMN `obra_nova` char(1) NOT NULL DEFAULT '' AFTER `obra_zona_azul`,
    MODIFY COLUMN `obra_inic_conc` char(1) NOT NULL DEFAULT '' AFTER `obra_nova`,
    MODIFY COLUMN `obra_contato` char(30) NOT NULL DEFAULT '' AFTER `obra_inic_conc`,
    MODIFY COLUMN `obra_cont_func` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `obra_contato`,
    MODIFY COLUMN `obra_cont_fone` int(9) unsigned NOT NULL DEFAULT '0' AFTER `obra_cont_func`,
    MODIFY COLUMN `obra_cont_cel` int(9) unsigned NOT NULL DEFAULT '0' AFTER `obra_cont_fone`,
    MODIFY COLUMN `obra_contato1` char(30) NOT NULL DEFAULT '' AFTER `obra_cont_cel`,
    MODIFY COLUMN `obra_cont1_func` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `obra_contato1`,
    MODIFY COLUMN `obra_cont1_fone` int(9) unsigned NOT NULL DEFAULT '0' AFTER `obra_cont1_func`,
    MODIFY COLUMN `obra_cont1_cel` int(9) unsigned NOT NULL DEFAULT '0' AFTER `obra_cont1_fone`,
    MODIFY COLUMN `obra_captado_v` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `obra_cont1_cel`,
    MODIFY COLUMN `obra_refer_aces` text AFTER `obra_captado_v`,
    MODIFY COLUMN `obra_pct_rp_cim` float(4,2) unsigned NOT NULL DEFAULT '0.00' AFTER `obra_refer_aces`,
    MODIFY COLUMN `obra_pct_rp_ped` float(4,2) unsigned NOT NULL DEFAULT '0.00' AFTER `obra_pct_rp_cim`,
    MODIFY COLUMN `obra_pct_rp_are` float(4,2) unsigned NOT NULL DEFAULT '0.00' AFTER `obra_pct_rp_ped`,
    MODIFY COLUMN `obra_pct_rp_obr` float(4,2) unsigned NOT NULL DEFAULT '0.00' AFTER `obra_pct_rp_are`,
    MODIFY COLUMN `obra_pct_rp_die` float(4,2) unsigned NOT NULL DEFAULT '0.00' AFTER `obra_pct_rp_obr`,
    MODIFY COLUMN `concorrente` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `obra_pct_rp_die`,
    MODIFY COLUMN `id_cadast` char(19) NOT NULL DEFAULT '' AFTER `concorrente`,
    MODIFY COLUMN `id_atual` char(19) NOT NULL DEFAULT '' AFTER `id_cadast`,
    MODIFY COLUMN `obra_resultado` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `id_atual`,
    MODIFY COLUMN `obra_desist` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `obra_resultado`,
    MODIFY COLUMN `obra_dt_desist` date AFTER `obra_desist`,
    MODIFY COLUMN `obra_usina_sec` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `obra_dt_desist`,
    MODIFY COLUMN `obra_km_usina_s` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `obra_usina_sec`,
    MODIFY COLUMN `volume_concreto` float(7,1) unsigned NOT NULL DEFAULT '0.0' AFTER `obra_km_usina_s`,
    MODIFY COLUMN `cond_pgto` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `volume_concreto`,
    MODIFY COLUMN `tipo_cobranca` smallint(4) unsigned NOT NULL DEFAULT '0' AFTER `cond_pgto`,
    MODIFY COLUMN `ganhou` char(1) NOT NULL DEFAULT '' AFTER `tipo_cobranca`,
    MODIFY COLUMN `reaj_id_solic` char(19) NOT NULL DEFAULT '' AFTER `ganhou`,
    MODIFY COLUMN `reaj_aprov_verb` char(1) NOT NULL DEFAULT '' AFTER `reaj_id_solic`,
    MODIFY COLUMN `reaj_id_aprov` char(19) NOT NULL DEFAULT '' AFTER `reaj_aprov_verb`,
    MODIFY COLUMN `obs` varchar(1000) NOT NULL AFTER `reaj_id_aprov`,
    MODIFY COLUMN `bco_cobranca` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `obs`,
    MODIFY COLUMN `reaj_sts_aprov` char(1) NOT NULL DEFAULT '' AFTER `bco_cobranca`,
    MODIFY COLUMN `reaj_cien_aprov` char(1) NOT NULL DEFAULT '' AFTER `reaj_sts_aprov`,
    MODIFY COLUMN `cp_prv_tipo` char(8) NOT NULL DEFAULT '' AFTER `reaj_cien_aprov`,
    MODIFY COLUMN `cp_prv_qtde` tinyint(1) unsigned NOT NULL DEFAULT '0' AFTER `cp_prv_tipo`,
    MODIFY COLUMN `cp_prv_intvl_m3` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `cp_prv_qtde`,
    MODIFY COLUMN `intinerante` char(1) NOT NULL DEFAULT '' AFTER `cp_prv_intvl_m3`,
    MODIFY COLUMN `seq` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `intinerante`,
    MODIFY COLUMN `obra_cont_ddd` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `seq`,
    MODIFY COLUMN `obra_cont_ddd1` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `obra_cont_ddd`,
    MODIFY COLUMN `vibr_qtde` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `obra_cont_ddd1`,
    MODIFY COLUMN `vibr_vlr_unit` float(6,2) unsigned NOT NULL DEFAULT '0.00' AFTER `vibr_qtde`,
    MODIFY COLUMN `volume_pcarga` float(5,1) unsigned NOT NULL DEFAULT '0.0' AFTER `vibr_vlr_unit`,
    MODIFY COLUMN `obra_cel_ddd` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `volume_pcarga`,
    MODIFY COLUMN `obra_cel_ddd1` tinyint(2) unsigned NOT NULL DEFAULT '0' AFTER `obra_cel_ddd`,
    MODIFY COLUMN `obra_radio` char(15) NOT NULL DEFAULT '' AFTER `obra_cel_ddd1`,
    MODIFY COLUMN `temp_ate_a_obra` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `obra_radio`,
    MODIFY COLUMN `temp_bt_na_obra` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `temp_ate_a_obra`,
    MODIFY COLUMN `url_mapa_obra` char(200) NOT NULL DEFAULT '' AFTER `temp_bt_na_obra`,
    MODIFY COLUMN `status_comercial` tinyint(1) unsigned NOT NULL DEFAULT '0' AFTER `url_mapa_obra`,
    MODIFY COLUMN `status_cadastro` tinyint(1) unsigned NOT NULL DEFAULT '0' AFTER `status_comercial`,
    MODIFY COLUMN `status_financeiro` tinyint(1) unsigned NOT NULL DEFAULT '0' AFTER `status_cadastro`,
    MODIFY COLUMN `status_engenharia` tinyint(1) unsigned NOT NULL DEFAULT '0' AFTER `status_financeiro`,
    MODIFY COLUMN `vlr_demais_servicos` double(8,2) unsigned NOT NULL DEFAULT '0.00' AFTER `status_engenharia`,
    MODIFY COLUMN `obra_cei` varchar(12) NOT NULL DEFAULT '' AFTER `vlr_demais_servicos`,
    MODIFY COLUMN `obra_obs` varchar(1000) NOT NULL DEFAULT '' AFTER `obra_cei`,
    MODIFY COLUMN `tempo_ciclo_prev` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `obra_obs`,
    MODIFY COLUMN `custo_proje_trans` float(6,2) unsigned NOT NULL DEFAULT '0.00' AFTER `tempo_ciclo_prev`,
    MODIFY COLUMN `obra_benef_fiscal` varchar(45) DEFAULT '' AFTER `custo_proje_trans`,
    MODIFY COLUMN `rota_padrao` char(36) AFTER `obra_benef_fiscal`,
    MODIFY COLUMN `email_resp_tecnico` varchar(255) DEFAULT '' AFTER `rota_padrao`,
    MODIFY COLUMN `tribcontrib_nfs` char(4) NOT NULL DEFAULT '' AFTER `email_resp_tecnico`,
    MODIFY COLUMN `id_imp_is` int(11) unsigned NOT NULL DEFAULT '0' AFTER `tribcontrib_nfs`,
    MODIFY COLUMN `id_imp_cbs` int(11) unsigned NOT NULL DEFAULT '0' AFTER `id_imp_is`,
    MODIFY COLUMN `id_imp_ibs` int(11) unsigned NOT NULL DEFAULT '0' AFTER `id_imp_cbs`,
    MODIFY COLUMN `volume_status_comercial` tinyint(4) NOT NULL DEFAULT '0' AFTER `id_imp_ibs`,
    MODIFY COLUMN `usa_adicional_zmrc` char(1) NOT NULL DEFAULT 'N' AFTER `volume_status_comercial`,
    MODIFY COLUMN `necessita_aprov_zmrc` char(1) NOT NULL DEFAULT 'N' AFTER `usa_adicional_zmrc`,
    MODIFY COLUMN `condicao_pagamento_status_comercial` tinyint(4) NOT NULL DEFAULT '0' AFTER `necessita_aprov_zmrc`,
    MODIFY COLUMN `tempo_descarga` smallint(3) unsigned NOT NULL DEFAULT '0' AFTER `condicao_pagamento_status_comercial`;