CREATE TABLE IF NOT EXISTS `topsys`.`con_proposta_item_log` (
	`id` CHAR(32) NOT NULL,
	`usina` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`obra_numero` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
	`proposta_numero` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
	`proposta_ano` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`sequencia` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`obra_versao` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`tabela` VARCHAR(55) NOT NULL DEFAULT '',
	`data` DATETIME NOT NULL,
	`usuario` VARCHAR(120) NOT NULL DEFAULT '',
	`source` VARCHAR(120) NOT NULL DEFAULT '',
	`script` TEXT NULL DEFAULT NULL,
	`payload` TEXT NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE,
	INDEX (`usina`, `obra_numero`) USING BTREE,
	INDEX (`data`) USING BTREE
);
